services:
  - type: web
    name: ai-chat-app-api
    runtime: dotnet
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/ChatApp.dll
    rootDir: backend/ChatApp/ChatApp
    plan: free